### ISSUE TITLE
Codifica errata

### ISSUE THREAD

**Issue by NeverWise** [drego85/TVHeadend-Script-TV-Guide#1]
Ciao! Ho notato la presenza di alcuni caratteri non codificati correttamente (apostrofi e lettere accentate) nei tre script python.
Ho risolto il problema modificando la riga di print da così
`print (file_content)`
a così
`print (file_content.decode('utf8'))`

Ciao e grazie per il tuo lavoro!

**Comment by drego85** [comment]
Grazie ;)

**Comment by drego85** [comment]
Fixed on commit [cc72a96](https://github.com/drego85/TVHeadend-Script-TV-Guide/commit/cc72a966139346cf7486bf350624f1891d63cc49)!
